import {
  AdminOrder,
  AdminCustomer,
  AdminCategory,
  AdminInventoryItem,
  StockHistoryLog,
  Coupon,
  StoreBanner,
  PaymentTransaction,
  StoreSettings,
  AdminUser,
} from './types';

export const INITIAL_ADMIN_USER: AdminUser = {
  id: 'usr-1',
  name: 'Ahmad Malik (Super Admin)',
  email: 'admin@ahmads.pk',
  role: 'super_admin',
  avatarUrl: '/src/assets/images/hero_luxury_formal_editorial_1790851112227.jpg',
  lastLogin: 'Today at 04:30 AM',
};

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: "AHMAD'S - House of Fashion",
  storePhone: '03326109729',
  storeEmail: 'info@ahmads.pk',
  storeAddress: 'Plot #103 Gulberg III, Lahore, Pakistan',
  currency: 'PKR',
  currencySymbol: 'Rs.',
  freeShippingThreshold: 15000,
  standardShippingFee: 500,
  taxRatePercent: 0,
  includeTaxInPrices: true,
  autoConfirmCOD: true,
  lowStockAlertThreshold: 5,
};

export const INITIAL_CATEGORIES: AdminCategory[] = [
  {
    id: 'cat-1',
    name: 'Noir Luxury',
    slug: 'noir-luxury',
    image: '/src/assets/images/naqsh_navy_velvet_1790851164132.jpg',
    productCount: 8,
    status: 'Enabled',
    description: 'Sumptuous micro velvet and raw silk ensembles in deep jewel tones.',
  },
  {
    id: 'cat-2',
    name: 'Luxury Formals',
    slug: 'luxury-formals',
    image: '/src/assets/images/lfora_zee_peach_organza_1790851132811.jpg',
    productCount: 16,
    status: 'Enabled',
    description: 'Pure organza and raw silk master pret with hand-embellished zardozi.',
  },
  {
    id: 'cat-3',
    name: 'Bridal Couture',
    slug: 'bridal-couture',
    image: '/src/assets/images/jahanara_champagne_kalidar_1790851177196.jpg',
    productCount: 12,
    status: 'Enabled',
    description: 'Sovereign kalidar gowns and peshwas adorned with micro crystals and pearls.',
  },
  {
    id: 'cat-4',
    name: 'Chiffon & Net',
    slug: 'chiffon-net',
    image: '/src/assets/images/noshmia_magenta_festive_1790851194273.jpg',
    productCount: 10,
    status: 'Enabled',
    description: 'Ethereal chiffon shirts with contrasting organza borders and gotta work.',
  },
];

export const INITIAL_ORDERS: AdminOrder[] = [
  {
    id: 'ord-101',
    orderNumber: 'AHM-89241',
    customerName: 'Fatima Siddiqui',
    customerEmail: 'fatima@example.com',
    customerPhone: '03001234567',
    shippingAddress: 'House 42, Block C, DHA Phase 5',
    city: 'Lahore',
    country: 'Pakistan',
    items: [
      {
        productId: 'lfora-zee-1912',
        productName: 'LFORA - ZEE-1912',
        productCode: 'ZEE-1912',
        image: '/src/assets/images/lfora_zee_peach_organza_1790851132811.jpg',
        selectedType: 'stitched',
        selectedSize: 'M',
        sleeveLining: 'with',
        quantity: 1,
        unitPrice: 17400, // 12900 + 4500 stitching
      },
    ],
    subtotal: 17400,
    discountAmount: 0,
    shippingFee: 0,
    totalAmount: 17400,
    paymentMethod: 'cod',
    paymentStatus: 'Pending',
    orderStatus: 'Processing',
    orderNotes: 'Please deliver before 6 PM on Saturday.',
    createdAt: '2026-10-01 03:15 AM',
    updatedAt: '2026-10-01 03:30 AM',
  },
  {
    id: 'ord-102',
    orderNumber: 'AHM-89240',
    customerName: 'Ayesha Khan',
    customerEmail: 'ayesha.k@example.co.uk',
    customerPhone: '+447911123456',
    shippingAddress: '14 Kensington High Street',
    city: 'London',
    country: 'United Kingdom',
    items: [
      {
        productId: 'meheka-zee-1918',
        productName: 'Meheka - ZEE-1918',
        productCode: 'ZEE-1918',
        image: '/src/assets/images/meheka_emerald_bridal_1790851149166.jpg',
        selectedType: 'stitched',
        selectedSize: 'L',
        sleeveLining: 'with',
        quantity: 1,
        unitPrice: 17400,
      },
      {
        productId: 'seraphina-1504',
        productName: 'Seraphina - 1504',
        productCode: '1504',
        image: '/src/assets/images/seraphina_black_formal_1790851270198.jpg',
        selectedType: 'unstitched',
        sleeveLining: 'without',
        quantity: 1,
        unitPrice: 10500,
      },
    ],
    subtotal: 27900,
    discountAmount: 2790, // 10% coupon
    shippingFee: 0,
    totalAmount: 25110,
    paymentMethod: 'card',
    paymentStatus: 'Paid',
    orderStatus: 'Shipped',
    createdAt: '2026-09-30 08:45 PM',
    updatedAt: '2026-10-01 01:00 AM',
  },
  {
    id: 'ord-103',
    orderNumber: 'AHM-89239',
    customerName: 'Zainab Tariq',
    customerEmail: 'zainab.t@example.com',
    customerPhone: '03219876543',
    shippingAddress: 'Apartment 4B, Falcon Complex, Gulberg III',
    city: 'Lahore',
    country: 'Pakistan',
    items: [
      {
        productId: 'jahanara-zee-1916',
        productName: 'Jahanara - ZEE-1916',
        productCode: 'ZEE-1916',
        image: '/src/assets/images/jahanara_champagne_kalidar_1790851177196.jpg',
        selectedType: 'stitched',
        selectedSize: 'S',
        sleeveLining: 'with',
        quantity: 1,
        unitPrice: 17400,
      },
    ],
    subtotal: 17400,
    discountAmount: 0,
    shippingFee: 0,
    totalAmount: 17400,
    paymentMethod: 'easypaisa_jazzcash',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    createdAt: '2026-09-29 11:20 AM',
    updatedAt: '2026-09-30 04:10 PM',
  },
  {
    id: 'ord-104',
    orderNumber: 'AHM-89238',
    customerName: 'Mariam Al-Mansoori',
    customerEmail: 'mariam.m@example.ae',
    customerPhone: '+971501234567',
    shippingAddress: 'Villa 12, Jumeirah 2',
    city: 'Dubai',
    country: 'United Arab Emirates',
    items: [
      {
        productId: 'naqsh-tbr-0004',
        productName: 'Naqsh - TBR-0004',
        productCode: 'TBR-0004',
        image: '/src/assets/images/naqsh_navy_velvet_1790851164132.jpg',
        selectedType: 'stitched',
        selectedSize: 'M',
        sleeveLining: 'with',
        quantity: 2,
        unitPrice: 15400,
      },
    ],
    subtotal: 30800,
    discountAmount: 3080,
    shippingFee: 0,
    totalAmount: 27720,
    paymentMethod: 'card',
    paymentStatus: 'Paid',
    orderStatus: 'Confirmed',
    createdAt: '2026-09-28 02:10 PM',
    updatedAt: '2026-09-28 03:00 PM',
  },
  {
    id: 'ord-105',
    orderNumber: 'AHM-89237',
    customerName: 'Sana Ahmed',
    customerEmail: 'sana.a@example.com',
    customerPhone: '03335551212',
    shippingAddress: 'Street 14, F-7/2',
    city: 'Islamabad',
    country: 'Pakistan',
    items: [
      {
        productId: 'celeste-1505',
        productName: 'Celeste - 1505',
        productCode: '1505',
        image: '/src/assets/images/celeste_ivory_organza_1790851282434.jpg',
        selectedType: 'unstitched',
        sleeveLining: 'without',
        quantity: 1,
        unitPrice: 9800,
      },
    ],
    subtotal: 9800,
    discountAmount: 0,
    shippingFee: 500,
    totalAmount: 10300,
    paymentMethod: 'cod',
    paymentStatus: 'Pending',
    orderStatus: 'Pending',
    createdAt: '2026-09-27 09:00 AM',
    updatedAt: '2026-09-27 09:00 AM',
  },
];

export const INITIAL_CUSTOMERS: AdminCustomer[] = [
  {
    id: 'cust-1',
    name: 'Fatima Siddiqui',
    email: 'fatima@example.com',
    phone: '03001234567',
    city: 'Lahore',
    country: 'Pakistan',
    totalOrders: 4,
    totalSpent: 64800,
    status: 'Active',
    joinedDate: '2025-11-10',
  },
  {
    id: 'cust-2',
    name: 'Ayesha Khan',
    email: 'ayesha.k@example.co.uk',
    phone: '+447911123456',
    city: 'London',
    country: 'United Kingdom',
    totalOrders: 3,
    totalSpent: 82400,
    status: 'Active',
    joinedDate: '2026-01-15',
  },
  {
    id: 'cust-3',
    name: 'Zainab Tariq',
    email: 'zainab.t@example.com',
    phone: '03219876543',
    city: 'Lahore',
    country: 'Pakistan',
    totalOrders: 2,
    totalSpent: 34800,
    status: 'Active',
    joinedDate: '2026-02-20',
  },
  {
    id: 'cust-4',
    name: 'Mariam Al-Mansoori',
    email: 'mariam.m@example.ae',
    phone: '+971501234567',
    city: 'Dubai',
    country: 'United Arab Emirates',
    totalOrders: 5,
    totalSpent: 112000,
    status: 'Active',
    joinedDate: '2025-08-04',
  },
  {
    id: 'cust-5',
    name: 'Sana Ahmed',
    email: 'sana.a@example.com',
    phone: '03335551212',
    city: 'Islamabad',
    country: 'Pakistan',
    totalOrders: 1,
    totalSpent: 10300,
    status: 'Active',
    joinedDate: '2026-09-27',
  },
];

export const INITIAL_INVENTORY: AdminInventoryItem[] = [
  {
    productId: 'lfora-zee-1912',
    productName: 'LFORA - ZEE-1912',
    sku: 'ZEE-1912',
    category: 'Luxury Formals',
    currentStock: 18,
    lowStockThreshold: 5,
    status: 'In Stock',
    lastRestocked: '2026-09-25',
  },
  {
    productId: 'meheka-zee-1918',
    productName: 'Meheka - ZEE-1918',
    sku: 'ZEE-1918',
    category: 'Luxury Formals',
    currentStock: 12,
    lowStockThreshold: 5,
    status: 'In Stock',
    lastRestocked: '2026-09-24',
  },
  {
    productId: 'naqsh-tbr-0004',
    productName: 'Naqsh - TBR-0004',
    sku: 'TBR-0004',
    category: 'Noir Luxury',
    currentStock: 3,
    lowStockThreshold: 5,
    status: 'Low Stock',
    lastRestocked: '2026-09-10',
  },
  {
    productId: 'jahanara-zee-1916',
    productName: 'Jahanara - ZEE-1916',
    sku: 'ZEE-1916',
    category: 'Luxury Formals',
    currentStock: 22,
    lowStockThreshold: 5,
    status: 'In Stock',
    lastRestocked: '2026-09-28',
  },
  {
    productId: 'noshmia-hyt-0601',
    productName: 'Noshmia HYT-0601',
    sku: 'HYT-0601',
    category: 'Luxury Formals',
    currentStock: 2,
    lowStockThreshold: 5,
    status: 'Low Stock',
    lastRestocked: '2026-08-15',
  },
  {
    productId: 'seraphina-1504',
    productName: 'Seraphina - 1504',
    sku: '1504',
    category: 'Noir Luxury',
    currentStock: 0,
    lowStockThreshold: 5,
    status: 'Out of Stock',
    lastRestocked: '2026-07-20',
  },
];

export const INITIAL_STOCK_LOGS: StockHistoryLog[] = [
  {
    id: 'log-1',
    sku: 'ZEE-1912',
    productName: 'LFORA - ZEE-1912',
    changeAmount: 20,
    previousStock: 0,
    newStock: 20,
    reason: 'Restock',
    adminUser: 'Ahmad Malik',
    timestamp: '2026-09-25 10:00 AM',
  },
  {
    id: 'log-2',
    sku: 'ZEE-1912',
    productName: 'LFORA - ZEE-1912',
    changeAmount: -1,
    previousStock: 20,
    newStock: 19,
    reason: 'Order Deduction',
    adminUser: 'System Auto',
    timestamp: '2026-09-30 02:15 PM',
  },
  {
    id: 'log-3',
    sku: '1504',
    productName: 'Seraphina - 1504',
    changeAmount: -5,
    previousStock: 5,
    newStock: 0,
    reason: 'Order Deduction',
    adminUser: 'System Auto',
    timestamp: '2026-09-28 06:40 PM',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'cpn-1',
    code: 'AHMAD10',
    type: 'percentage',
    value: 10,
    minOrderAmount: 10000,
    usageLimit: 500,
    usedCount: 142,
    expiryDate: '2026-12-31',
    status: 'Active',
  },
  {
    id: 'cpn-2',
    code: 'COUTURE15',
    type: 'percentage',
    value: 15,
    minOrderAmount: 20000,
    usageLimit: 100,
    usedCount: 38,
    expiryDate: '2026-11-30',
    status: 'Active',
  },
  {
    id: 'cpn-3',
    code: 'EID2000',
    type: 'fixed',
    value: 2000,
    minOrderAmount: 25000,
    usageLimit: 50,
    usedCount: 50,
    expiryDate: '2026-06-30',
    status: 'Expired',
  },
];

export const INITIAL_BANNERS: StoreBanner[] = [
  {
    id: 'ban-1',
    title: 'NOIR LUXURY & LUXURY FORMALS',
    subtitle: 'Handcrafted Pakistani Pret, Chiffon & Bridal Couture',
    announcementText: 'Shop Worldwide Stress-Free! Customs, Duties & Taxes are already covered in your shipping.',
    bannerImage: '/src/assets/images/hero_luxury_formal_editorial_1790851112227.jpg',
    isActive: true,
  },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'pay-1',
    transactionId: 'TXN-984210',
    orderNumber: 'AHM-89240',
    customerName: 'Ayesha Khan',
    paymentMethod: 'card',
    amount: 25110,
    paymentStatus: 'Paid',
    date: '2026-09-30 08:45 PM',
  },
  {
    id: 'pay-2',
    transactionId: 'TXN-984209',
    orderNumber: 'AHM-89239',
    customerName: 'Zainab Tariq',
    paymentMethod: 'easypaisa_jazzcash',
    amount: 17400,
    paymentStatus: 'Paid',
    date: '2026-09-29 11:20 AM',
  },
  {
    id: 'pay-3',
    transactionId: 'TXN-984208',
    orderNumber: 'AHM-89238',
    customerName: 'Mariam Al-Mansoori',
    paymentMethod: 'card',
    amount: 27720,
    paymentStatus: 'Paid',
    date: '2026-09-28 02:10 PM',
  },
  {
    id: 'pay-4',
    transactionId: 'COD-PENDING-101',
    orderNumber: 'AHM-89241',
    customerName: 'Fatima Siddiqui',
    paymentMethod: 'cod',
    amount: 17400,
    paymentStatus: 'Pending',
    date: '2026-10-01 03:15 AM',
  },
];
